[tool.poetry]
name = "vsdesk-bot"
version = "0.1.0"
description = ""
authors = ["pavelkoA <115475612+pavelkoA@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
